// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebRecipe.Models;

#nullable disable

namespace WebRecipe.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20220423215707_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebRecipe.Models.Category", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = "srcy",
                            Description = "Starchy foods are a good source of energy and the main source of a range of nutrients in our diet. As well as starch, they contain fibre, calcium, iron and B vitamins. Some people think starchy foods are fattening, but gram for gram they contain fewer than half the calories of fat.",
                            Name = "Starchy"
                        },
                        new
                        {
                            CategoryID = "favt",
                            Description = "A diet rich in vegetables and fruits can lower blood pressure, reduce the risk of heart disease and stroke, prevent some types of cancer, lower risk of eye and digestive problems, and have a positive effect upon blood sugar, which can help keep appetite in check.",
                            Name = "Fruit And Vegetables"
                        },
                        new
                        {
                            CategoryID = "dssr",
                            Description = "Their presence on the menu makes us feel satisfied after a meal, and compensates for low blood sugar. The desire to improve your mood by ingesting sugar can also be a factor. Sweet snacks increase our production of the so-called hormone of happiness. Your habits also play an important role.",
                            Name = "Dessert"
                        },
                        new
                        {
                            CategoryID = "prtn",
                            Description = "You need protein in your diet to help your body repair cells and make new ones. Protein is also important for growth and development in children, teens, and pregnant women.",
                            Name = "Protein"
                        },
                        new
                        {
                            CategoryID = "grns",
                            Description = "Grains are important sources of many nutrients, including fiber, B vitamins (thiamin, riboflavin, niacin and folate) and minerals (iron, magnesium and selenium). People who eat whole grains as part of a healthy diet have a reduced risk of some chronic diseases.",
                            Name = "Grains"
                        });
                });

            modelBuilder.Entity("WebRecipe.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeID"), 1L, 1);

                    b.Property<string>("CategoryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("FoodImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.HasKey("RecipeID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeID = 1,
                            CategoryID = "favt",
                            Description = "The perfect fruit salad for a backyard bbq or any occasion. There are never leftovers! This is one of my favorite fruit salad recipes, as I think the sauce really makes it. This salad is tastier the longer you can let it soak in its juices. I prefer 3 to 4 hours in the refrigerator before I serve it. Enjoy.",
                            FoodImage = "fruinsal",
                            Name = "Fruit Salad",
                            PreparationTime = 45,
                            Rating = 4,
                            Steps = "Bring orange juice, lemon juice, brown sugar, orange zest, and lemon zest to a boil in a saucepan over medium-high heat. Reduce heat to medium-low, and simmer until slightly thickened, about 5 minutes. Remove from heat, and stir in vanilla extract. Set aside to cool.|Layer the fruit in a large, clear glass bowl in this order: pineapple, strawberries, kiwi fruit, bananas, oranges, grapes, and blueberries. Pour the cooled sauce over the fruit. Cover and refrigerate for 3 to 4 hours before serving."
                        },
                        new
                        {
                            RecipeID = 2,
                            CategoryID = "dssr",
                            Description = "This is a no-bake pudding dessert that's so quick and easy to make--everyone loves it. I always keep the ingredients on hand in case I need a quick dessert. It's best if it sits overnight before serving.",
                            FoodImage = "chocdess",
                            Name = "Chocolate Eclair Dessert",
                            PreparationTime = 90,
                            Rating = 5,
                            Steps = "Line the bottom of a 9x13-inch pan with graham crackers.|In a large bowl, combine pudding mix and milk; stir well. Mix whipped topping into pudding mixture. Spread half of mixture over graham cracker layer. Top with another layer of graham crackers and the remaining pudding.|Top all with a final layer of graham crackers and frost with chocolate frosting. Refrigerate at least two hours before serving to allow the graham crackers to soften."
                        },
                        new
                        {
                            RecipeID = 3,
                            CategoryID = "grns",
                            Description = "Here's a delicious zucchini bread with just the right touch of whole grains added. Perfect with walnuts or even chopped pecans.",
                            FoodImage = "brgrns",
                            Name = "Zucchini Banana Multi-Grain Bread",
                            PreparationTime = 20,
                            Rating = 4,
                            Steps = "Place flour, cranberries, yogurt, water, honey, butter, yeast, salt, and orange oil in the pan of a bread machine in the order recommended by the manufacturer. Select 'light crust' setting; press Start."
                        },
                        new
                        {
                            RecipeID = 4,
                            CategoryID = "prtn",
                            Description = "It takes a little work, but it is worth it.",
                            FoodImage = "lasagimg",
                            Name = "Lasagna",
                            PreparationTime = 180,
                            Rating = 5,
                            Steps = "In a Dutch oven, cook sausage, ground beef, onion, and garlic over medium heat until well browned. Stir in crushed tomatoes, tomato paste, tomato sauce, and water. Season with sugar, basil, fennel seeds, Italian seasoning, 1 teaspoon salt, pepper, and 2 tablespoons parsley. Simmer, covered, for about 1 1/2 hours, stirring occasionally.|Bring a large pot of lightly salted water to a boil. Cook lasagna noodles in boiling water for 8 to 10 minutes. Drain noodles, and rinse with cold water. In a mixing bowl, combine ricotta cheese with egg, remaining parsley, and 1/2 teaspoon salt.|Preheat oven to 375 degrees F (190 degrees C).|To assemble, spread 1 1/2 cups of meat sauce in the bottom of a 9x13-inch baking dish. Arrange 6 noodles lengthwise over meat sauce. Spread with one half of the ricotta cheese mixture. Top with a third of mozzarella cheese slices. Spoon 1 1/2 cups meat sauce over mozzarella, and sprinkle with 1/4 cup Parmesan cheese. Repeat layers, and top with remaining mozzarella and Parmesan cheese. Cover with foil: to prevent sticking, either spray foil with cooking spray, or make sure the foil does not touch the cheese.|Bake in preheated oven for 25 minutes. Remove foil, and bake an additional 25 minutes. Cool for 15 minutes before serving."
                        },
                        new
                        {
                            RecipeID = 5,
                            CategoryID = "srcy",
                            Description = "This pizza uses hummus instead of the usual red sauce—a unique and healthy pizza for those bored with the traditional. Top with your favorite veggies and cheese.",
                            FoodImage = "vegpzz",
                            Name = "Hummus Pizza",
                            PreparationTime = 60,
                            Rating = 4,
                            Steps = "Preheat the oven to 475 degrees C (220 degrees C).|Roll out pizza crust and place on a pizza pan or baking sheet. Spread a thin layer of hummus over the crust. Arrange sliced peppers and broccoli over the hummus, and top with shredded cheese.|Bake in the preheated oven until the crust is golden brown and cheese is melted in the center, 10 to 15 minutes. Slice and serve."
                        });
                });

            modelBuilder.Entity("WebRecipe.Models.Recipe", b =>
                {
                    b.HasOne("WebRecipe.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebRecipe.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
